# Source: jxboot-helmfile-resources/templates/ingress-config-configmap.yaml
apiVersion: v1
data:
  domain: "aacb3fb943e324e2f8cc5d24574f599e-8c7484d81c94a67a.elb.us-east-1.amazonaws.com"
  email: ""
  exposer: "Ingress"
  issuer: ""
  tls: "false"
kind: ConfigMap
metadata:
  name: ingress-config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
