apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: test-jenkins-x
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "834667370484"
    provider: eks
    region: us-east-1
    registry: ecr.io
  environments:
  - key: dev
    owner: deriv-org
    repository: jx3-eks-vault
  - key: staging
  - key: production
  ingress:
    domain: aacb3fb943e324e2f8cc5d24574f599e-8c7484d81c94a67a.elb.us-east-1.amazonaws.com
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: goku-bot-user
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-test-jenkins-x-20201223125813386400000001
  - name: reports
    url: s3://reports-test-jenkins-x-20201223125813400000000006
  - name: repository
    url: s3://repository-test-jenkins-x-20201223125813395800000003
  terraform: true
  vault:
    aws:
      dynamoDBRegion: us-east-1
      dynamoDBTable: vault-unseal-test-jenkins-x-0mFigKli
      kmsKeyId: c7139ce5-e4f0-455d-a357-d59bec8ac6a2
      kmsRegion: us-east-1
      s3Bucket: vault-unseal-test-jenkins-x-20201223125813398300000005
      s3Region: us-east-1
  webhook: lighthouse
