filepath: ""
namespace: jx-staging
repositories:
- name: dev
  url: http://chartmuseum-jx.build.regentmarkets.com/
releases:
- chart: dev/toto
  version: 0.0.1
  name: toto
templates: {}
renderedvalues: {}
