filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://chartmuseum-jx.build.regentmarkets.com/
releases:
- chart: dev/sta
  version: 0.0.2
  name: sta
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
