apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        deriv-org/jx3-eks-vault: true
        deriv-org/test-d-go: true
        goku-bot-user/binary-bot: true
        goku-bot-user/new-go: true
        goku-bot-user/new-lang: true
        goku-bot-user/toto: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        deriv-org/jx3-eks-vault: merge
        deriv-org/test-d-go: merge
        goku-bot-user/binary-bot: merge
        goku-bot-user/new-go: merge
        goku-bot-user/new-lang: merge
        goku-bot-user/toto: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - deriv-org/jx3-eks-vault
        - deriv-org/test-d-go
        - goku-bot-user/binary-bot
        - goku-bot-user/new-go
        - goku-bot-user/new-lang
        - goku-bot-user/toto
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - deriv-org/jx3-eks-vault
        - deriv-org/test-d-go
        - goku-bot-user/binary-bot
        - goku-bot-user/new-go
        - goku-bot-user/new-lang
        - goku-bot-user/toto
      target_url: http://dashboard-jx.build.regentmarkets.com
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
